CREATE DATABASE mediaAcquisitionDB;

USE mediaAcquisitionDB;

CREATE TABLE Music (
  ID SERIAL PRIMARY KEY,
  YoutubeLink NVARCHAR(500) UNIQUE NOT NULL
);

CREATE TABLE Artists (
  ID SERIAL PRIMARY KEY,
  Artist NVARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE Writers (
ID SERIAL PRIMARY KEY,
Writer NVARCHAR(250) NOT NULL
);

CREATE TABLE RecordLabels (
ID SERIAL PRIMARY KEY,
RecordLabel NVARCHAR(250) NOT NULL
);

CREATE TABLE Producers (
ID SERIAL PRIMARY KEY,
Producer NVARCHAR(250) NOT NULL
);

CREATE TABLE Genres (
ID SERIAL PRIMARY KEY,
Genre NVARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE Categories (
ID SERIAL PRIMARY KEY,
Category NVARCHAR(250) NOT NULL
);

CREATE TABLE Albums (
ID SERIAL PRIMARY KEY,
Album NVARCHAR(250) NOT NULL
);

CREATE TABLE MetaData (
  ID SERIAL PRIMARY KEY,
  ArtistID BIGINT UNSIGNED,
  FOREIGN KEY (ArtistID) REFERENCES Artists(ID),
  GenreID BIGINT UNSIGNED,
  FOREIGN KEY (GenreID) REFERENCES Genres(ID),
  AlbumID BIGINT UNSIGNED,
  FOREIGN KEY (AlbumID) REFERENCES Albums(ID),
  ReleaseDate DATE,
  Title NVARCHAR(250) NOT NULL,
  CategoryID BIGINT UNSIGNED,
  FOREIGN KEY (CategoryID) REFERENCES Categories(ID),
  ProducerID BIGINT UNSIGNED,
  FOREIGN KEY (ProducerID) REFERENCES Producers(ID),
  Co_artistID BIGINT UNSIGNED,
  FOREIGN KEY (Co_artistID) REFERENCES Artists(ID),
  RecordLabelID BIGINT UNSIGNED,
  FOREIGN KEY (RecordLabelID) REFERENCES RecordLabels(ID),
  WritersID BIGINT UNSIGNED,
  FOREIGN KEY (WritersID) REFERENCES Writers(ID),
  SongDuration NVARCHAR(50)
);

CREATE TABLE MetaDataToMusic (
  MetaDataID BIGINT UNSIGNED,
  FOREIGN KEY (MetaDataID) REFERENCES MetaData(ID),
  MusicID BIGINT UNSIGNED,
  FOREIGN KEY (MusicID) REFERENCES Music(ID)
);

CREATE TABLE MusicLog (
  MusicID BIGINT UNSIGNED,
  FOREIGN KEY(MusicID) REFERENCES Music(ID),
  Event ENUM('Created', 'Deleted'),
  Time TIMESTAMP
);

CREATE TABLE MusicStorage (
  MusicID BIGINT UNSIGNED,
  FOREIGN KEY(MusicID) REFERENCES Music(ID),
  FilePath NVARCHAR(500) UNIQUE NOT NULL,
  ThumbnailPath NVARCHAR(500)
);

ALTER user 'root' IDENTIFIED WITH mysql_native_password BY '';
flush privileges;


/*
//Tables for implementation of administration part
CREATE TABLE MusicAdmin (
  MusicID  BIGINT UNSIGNED,
  FOREIGN KEY(MusicID) REFERENCES Music(ID),
  Flagcount INT,
  Unflaggable BOOLEAN
);

CREATE TABLE CreatedBy (
  MusicID BIGINT UNSIGNED,
  FOREIGN KEY(MusicID) REFERENCES Music(ID),
  UserID BIGINT UNSIGNED
);

CREATE TABLE Deleted_by (
  MusicID BIGINT UNSIGNED,
  FOREIGN KEY(MusicID) REFERENCES Music(ID),
  UserID BIGINT UNSIGNED
);*/